services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
    - namenode:/hadoop/dfs/name
    environment:
    - CLUSTER_NAME=test
    env_file:
    - ./hadoop.env
    ports:
    - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
    - datanode:/hadoop/dfs/data
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
    - "50075:50075"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
    - ./hadoop.env
    ports:
    - 8088:8088

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
    - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
    - historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
    - ./hadoop.env
    ports:
    - 8188:8188
  
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
      TEZ_CONF_DIR: /opt/tez/conf
      HADOOP_CLASSPATH: /opt/tez/conf:/opt/tez/*:/opt/tez/lib/*
    depends_on:
    - tez
    volumes:
    - tez-libs:/opt/tez
    ports:
    - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
    - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
    - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

  pig:
    image: abdeod/apache-pig:0.17.0
    environment:
      HADOOP_CONF_DIR: /etc/hadoop
    volumes:
      - ./config-pig:/etc/hadoop
    depends_on:
      - namenode
      - datanode
    command: /bin/bash
    stdin_open: true
    tty: true

  tez:
    image: abdeod/apache-tez:hadoop2.7.4-java8
    container_name: tez
    volumes:
    - ./config-tez/tez-site.xml:/opt/tez/conf/tez-site.xml
    - ./config-tez/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    - ./config-tez/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
    - ./config-tez/init-tez-lib.sh:/opt/init-tez-lib.sh
    - tez-libs:/opt/tez
    depends_on:
    - namenode
    - resourcemanager
    - nodemanager
    command: bash -c "bash /opt/init-tez-lib.sh && bash"
    stdin_open: true
    tty: true

  spark:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark
    ports:
    - "8080:8080"
    - "7077:7077"
    environment:
    - INIT_DAEMON_STEP=setup_spark
    volumes:
    - spark-dist:/spark

  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker
    depends_on:
    - spark
    ports:
    - "8081:8081"
    environment:
    - SPARK_MASTER=spark://spark:7077
    volumes:
    - spark-dist:/spark

  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    environment:
      ZEPPELIN_ADDR: "0.0.0.0"
      ZEPPELIN_PORT: 8085
      SPARK_HOME: /opt/spark
      SPARK_MASTER: spark://spark:7077
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    volumes:
    - zeppelin-data:/zeppelin
    - spark-dist:/opt/spark
    ports:
    - "8085:8085"
    depends_on:
    - spark

volumes:
  namenode:
  datanode:
  historyserver:
  tez-libs:
  spark-dist:
  zeppelin-data: